apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name}}-app-config
  namespace: {{ .Values.common.namespace }}
data:
{{- range $k, $v := .Values.todoapp.configs }}
  {{ $k }}: {{ $v | toString | quote }}
{{- end }}